FROM nginx:alpine
COPY configs/nginx/gateway-nginx.conf /etc/nginx/nginx.conf
COPY data/service-responses/payment-nginx/index.html /usr/share/nginx/html/index.html
HEALTHCHECK CMD wget --spider -q http://localhost:8083 || exit 1
